<a href="https://colab.research.google.com/github/SpellOnYou/bayesian/blob/master/Kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$SSB = SST - SSW$$
$$SSW:\ Bewteen\ Sum\ of\ squares\ =\ \sum \sum \left\|x-K_{i} \right\|^2$$

In [1]:
km = function(X, K, maxiter = 50, tol = 1e-8) {
    N = nrow(X)
    p = ncol(X)
    mu0 = t(X[sample.int(N, K),])
    # input data (row) X the number of cluster(col) - maxtrix, filled with 0
    d = data.frame(matrix(0, N, K))
    h = data.frame(matrix(0, N ,K))
    for(i in 1:maxiter) {
        for(n in 1:N) {
            for(k in 1:K) {
                d[n, k] = sum((X[n,] - mu0[,k])^2)
            }
            h[n, ] = min(d[n,]) == d[n,]
        }
        # centroid update
        mu1 = data.frame(matrix(0, p, K))
        for(j in 1:p){
            for(k in 1:K) {
                 mu1[j, k] = sum(h[,k] * X[,j]) / sum(h[,k])
            }
        }

        ## stop condition
        if(sum(abs(1 - mu0/mu1)) < tol) break
        mu0 = mu1
    }
    list(clusters = h, iter = i, centroid = mu1)
}

In [9]:
n = 100
X = matrix(data = c(rnorm(n), rnorm(n), rnorm(n)), ncol = 3 ); K = 3

In [11]:
dim(X)

[1] 100   3

In [12]:
km(X, K)

ERROR while rich displaying an object: Error in vapply(seq_along(mapped), function(i) {: 길이가 반드시 1이어야 하지만,
FUN(X[[1]])의 결과는 길이 0 입니다

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. mime2repr[[mime]](obj)
8. repr_markdown.list(obj)
9. repr_list_generic(obj, "markdown", "%s. %s\n", "$%s\n:   %s\n",
 .     "**$%s** = %s", "%s\n\n", numeric.item = "[[%s]]\n:   %s\n",
 .     item.uses.numbers = TRUE, escape.FUN = html.escape)
10. vapply(seq_along(mapped), function(i) {
  .     nm <- nms[[i]]
  .     if (is.na(nm) || nchar(nm) == 0) {
  .         sprintf(numeric.item, i, mapped[[i]])
  .     }
  .     else {
  .         sprintf(named.item, nms[[i]], mapped[[i]])
  .     }
  . }, character(1))

$clusters
    X1 X2 X3
1    0  1  0
2    0  1  0
3    0  1  0
4    0  0  1
5    0  0  1
6    1  0  0
7    0  1  0
8    0  0  1
9    0  0  1
10   1  0  0
11   0  0  1
12   0  0  1
13   0  0  1
14   0  0  1
15   1  0  0
16   1  0  0
17   0  1  0
18   0  0  1
19   0  0  1
20   0  1  0
21   0  0  1
22   0  1  0
23   1  0  0
24   0  0  1
25   0  1  0
26   0  0  1
27   0  0  1
28   1  0  0
29   0  1  0
30   1  0  0
31   1  0  0
32   0  0  1
33   1  0  0
34   1  0  0
35   0  1  0
36   0  1  0
37   1  0  0
38   0  1  0
39   1  0  0
40   0  0  1
41   0  0  1
42   1  0  0
43   0  1  0
44   1  0  0
45   1  0  0
46   0  0  1
47   0  1  0
48   1  0  0
49   1  0  0
50   1  0  0
51   0  0  1
52   0  0  1
53   1  0  0
54   0  0  1
55   1  0  0
56   1  0  0
57   1  0  0
58   0  0  1
59   1  0  0
60   0  1  0
61   0  0  1
62   0  0  1
63   1  0  0
64   0  1  0
65   0  0  1
66   1  0  0
67   0  0  1
68   1  0  0
69   0  0  1
70   1  0  0
71   1  0  0
72   0  0  1
73   0  0  1
74   0  0  1
75   0  1  0
76   0  0  1
77   0  0  1
78   0  0  1
79   0  0  1
80   0  0  1
81   0  0  1
82   0  1  0
83   1  0  0
84   0  1  0
85   0  0  1
86   0  1  0
87   0  0  1
88   0  0  1
89   0  0  1
90   0  0  1
91   0  1  0
92   0  1  0
93   0  1  0
94   0  0  1
95   1  0  0
96   1  0  0
97   0  0  1
98   1  0  0
99   1  0  0
100  1  0  0

$iter
[1] 7

$centroid
         X1         X2         X3
1 0.5170893 -0.1676719 -0.3928535
2 0.1306405  1.1246370 -0.6530845
3 1.0528176 -0.5617875 -0.6248876